project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - teaching.qmd

format:
  html:
    theme: lux # cosmo
    css: styles.css
    toc: false

editor: visual

